// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package api_test

type mockStore struct {
	HasCredentialsCalled chan bool
	HasCredentialsOutput struct {
		Has chan bool
	}
	SetCredentialsCalled chan bool
	SetCredentialsInput  struct {
		User, Pass chan string
	}
	SetCredentialsOutput struct {
		Err chan error
	}
}

func newMockStore() *mockStore {
	m := &mockStore{}
	m.HasCredentialsCalled = make(chan bool, 100)
	m.HasCredentialsOutput.Has = make(chan bool, 100)
	m.SetCredentialsCalled = make(chan bool, 100)
	m.SetCredentialsInput.User = make(chan string, 100)
	m.SetCredentialsInput.Pass = make(chan string, 100)
	m.SetCredentialsOutput.Err = make(chan error, 100)
	return m
}
func (m *mockStore) HasCredentials() (has bool) {
	m.HasCredentialsCalled <- true
	return <-m.HasCredentialsOutput.Has
}
func (m *mockStore) SetCredentials(user, pass string) (err error) {
	m.SetCredentialsCalled <- true
	m.SetCredentialsInput.User <- user
	m.SetCredentialsInput.Pass <- pass
	return <-m.SetCredentialsOutput.Err
}
