// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package stream

type mockTwitchUserIDFetcher struct {
	UserIDCalled chan bool
	UserIDInput  struct {
		Username chan string
	}
	UserIDOutput struct {
		UserID chan int
		Err    chan error
	}
}

func newMockTwitchUserIDFetcher() *mockTwitchUserIDFetcher {
	m := &mockTwitchUserIDFetcher{}
	m.UserIDCalled = make(chan bool, 100)
	m.UserIDInput.Username = make(chan string, 100)
	m.UserIDOutput.UserID = make(chan int, 100)
	m.UserIDOutput.Err = make(chan error, 100)
	return m
}
func (m *mockTwitchUserIDFetcher) UserID(username string) (userID int, err error) {
	m.UserIDCalled <- true
	m.UserIDInput.Username <- username
	return <-m.UserIDOutput.UserID, <-m.UserIDOutput.Err
}
