// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package bot_test

import "anubot/stream"

type mockFeature struct {
	HandleMessageCalled chan bool
	HandleMessageInput  struct {
		Ms chan stream.RXMessage
	}
	StartCalled chan bool
	StopCalled  chan bool
}

func newMockFeature() *mockFeature {
	m := &mockFeature{}
	m.HandleMessageCalled = make(chan bool, 100)
	m.HandleMessageInput.Ms = make(chan stream.RXMessage, 100)
	m.StartCalled = make(chan bool, 100)
	m.StopCalled = make(chan bool, 100)
	return m
}
func (m *mockFeature) HandleMessage(ms stream.RXMessage) {
	m.HandleMessageCalled <- true
	m.HandleMessageInput.Ms <- ms
}
func (m *mockFeature) Start() {
	m.StartCalled <- true
}
func (m *mockFeature) Stop() {
	m.StopCalled <- true
}
