// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package bot_test

import "anubot/bot"

type mockDispatcher struct {
	DispatchCalled chan bool
	DispatchInput  struct {
		Msg chan bot.Message
	}
}

func newMockDispatcher() *mockDispatcher {
	m := &mockDispatcher{}
	m.DispatchCalled = make(chan bool, 100)
	m.DispatchInput.Msg = make(chan bot.Message, 100)
	return m
}
func (m *mockDispatcher) Dispatch(msg bot.Message) {
	m.DispatchCalled <- true
	m.DispatchInput.Msg <- msg
}
